// <auto-generated />
using System.Collections.Generic;
using JsonColumns.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JsonColumns.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260929173332_AddDistributorComplexCollection")]
    partial class AddDistributorComplexCollection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JsonColumns.Api.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "BillingAddress", "JsonColumns.Api.Models.Customer.BillingAddress#Address", b1 =>
                        {
                            b1.Property<string>("City")
                                .IsRequired();

                            b1.Property<string>("Country")
                                .IsRequired();

                            b1.Property<string>("PostalCode")
                                .IsRequired();

                            b1.Property<string>("Street")
                                .IsRequired();

                            b1
                                .ToJson("BillingAddress")
                                .HasColumnType("nvarchar(max)");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ShippingAddress", "JsonColumns.Api.Models.Customer.ShippingAddress#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired();

                            b1.Property<string>("Country")
                                .IsRequired();

                            b1.Property<string>("PostalCode")
                                .IsRequired();

                            b1.Property<string>("Street")
                                .IsRequired();

                            b1
                                .ToJson("ShippingAddress")
                                .HasColumnType("nvarchar(max)");
                        });

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("JsonColumns.Api.Models.Distributor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "ShippingCenters", "JsonColumns.Api.Models.Distributor.ShippingCenters#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired();

                            b1.Property<string>("Country")
                                .IsRequired();

                            b1.Property<string>("PostalCode")
                                .IsRequired();

                            b1.Property<string>("Street")
                                .IsRequired();

                            b1
                                .ToJson("ShippingCenters")
                                .HasColumnType("nvarchar(max)");
                        });

                    b.HasKey("Id");

                    b.ToTable("Distributors");
                });
#pragma warning restore 612, 618
        }
    }
}
